name: CI Pipeline
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  storybook-tests:
    name: Storybook Component Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook --reporter html --output storybook-report.html"
      - name: Move test report into Storybook static folder
        run: cp storybook-report.html storybook-static/test-report.html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
           name: storybook-report
           path: storybook-report.html
  playwright-tests:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    needs: storybook-tests
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r playwright-python/requirements.txt
        - name: Install Playwright dependencies
          run: |
            python -m playwright install
        - name: Start React app on localhost:3001
          run: |
            npm ci
            npm run build
            npx serve -s build -l 3001 &
            npx wait-on http://localhost:3001
        - name: Run Playwright tests (Python)
          run: |
            rm -rf playwright-report/
            pytest playwright-python/ --html=playwright-report/report.html --self-contained-html --maxfail=1 --disable-warnings -q
        - name: Upload Playwright HTML report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: playwright-HTML-report
            path: playwright-report/report.html
            retention-days: 30